Pin the manylinux image and try installing from pypi

diff --git a/.github/workflows/wheels.yaml b/.github/workflows/wheels.yaml
--- a/.github/workflows/wheels.yaml
+++ b/.github/workflows/wheels.yaml
@@ -34,7 +34,7 @@ jobs:
         run: |
           python -m cibuildwheel --output-dir wheelhouse
         env:
-          CIBW_MANYLINUX_X86_64_IMAGE: quay.io/pypa/manylinux2014_x86_64:latest
+          CIBW_MANYLINUX_X86_64_IMAGE: quay.io/pypa/manylinux2014_x86_64:2021-05-30-d4af1a5
           CIBW_BEFORE_BUILD: python -m pip install cmake
           CIBW_BEFORE_BUILD_LINUX: yum install -y openblas-devel.x86_64 gcc
           CIBW_BEFORE_BUILD_MACOS: brew install openblas gcc
@@ -101,11 +101,18 @@ jobs:
       - name: Install test requirements
         run: |
           python -m pip install -r test-requirements.txt
-          sleep 90
 
       - name: Install from TestPyPI
         run: |
-          python -m pip install -i https://test.pypi.org/simple/ -r version.txt
+          max_retry=5
+          counter=0
+          until python -m pip install -i https://test.pypi.org/simple/ -r version.txt
+          do
+             sleep 30
+             [[ counter -eq $max_retry ]] && echo "Failed!" && exit 1
+             echo "Trying again. Try #$counter"
+             ((counter++))
+          done
 
       - name: Run a single test
         # not using pytest because pytest imports dqc from the local directory
